#!/bin/bash

if [ -f configure.ac.in ]; then
	CONFIGURE_AC=configure.ac.in
else
	CONFIGURE_AC=configure.ac
fi

GETTEXT_PACKAGE=$(grep 'GETTEXT_PACKAGE=' $CONFIGURE_AC | cut -d= -f2)
PLUGIN_AUTHOR=$(grep 'PLUGIN_AUTHOR' $CONFIGURE_AC | cut -d\" -f2)
PLUGIN_ID=$(grep 'PLUGIN_ID' $CONFIGURE_AC | cut -d\" -f2)
PLUGIN_STATIC_NAME=$(grep 'PLUGIN_STATIC_NAME' $CONFIGURE_AC | cut -d\" -f2)
PLUGIN_WEBSITE=$(grep 'PLUGIN_WEBSITE' $CONFIGURE_AC | cut -d\" -f2)
PLUGIN_VERSION=$(./scripts/gen-version.sh)


cat << EOF
/* Generated by scripts/gen-mingw-config_h.sh
 * from files VERSION and $CONFIGURE_AC.
 */
#define ENABLE_NLS 1
#define GETTEXT_PACKAGE "$GETTEXT_PACKAGE"
#define PLUGIN_AUTHOR "$PLUGIN_AUTHOR"
#define PLUGIN_ID "$PLUGIN_ID"
#define PLUGIN_STATIC_NAME "$PLUGIN_STATIC_NAME"
#define PLUGIN_VERSION "$PLUGIN_VERSION"
#define PLUGIN_WEBSITE "$PLUGIN_WEBSITE"
EOF
